---
# This is my first playbook

# HEADER SECTION
 - name: This playbook will create a file
   hosts: webservers
   vars:
     - myname: Goutham

# TASK SECTION
   tasks:
     - name: To print the variable data
       debug:
         var: myname

     - name: To print the variable data
       debug:
         var: ansible_distribution

     - name: To print the variable data
       debug:
         var: ansible_default_ipv4.macaddress

     - name: To print the variable data
       debug:
         var: ansible_architecture

     - name: To print the variable data
       debug:
         var: ansible_processor_cores

     - name: To print the variable data
       debug:
         var: ansible_memtotal_mb

     - name: To print the variable data
       debug:
         var: ansible_env.java_home

     - name: To install apache webserver in ubuntu
       apt:
         name: apache2
         state: present
       when: ( ansible_distribution == "Ubuntu" and ansible_memtotal_mb > 1000 )
