---
- name: Run the playbook on the local ansible controller
  hosts: localhost
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: /opt/
    register: find_output

  - debug:
     var: find_output
