---
# This Playbook will define vairables and use them across the code

# HEADER SECTION
 - name: This play will install a package and copy a file
   hosts: webservers
   vars:
     mypackage: vim
     myfile: helloworld.yaml

# TASK SECTION
   tasks:
     - name: To install package named "{{ mypackage }}"
       yum:
         name: "{{ mypackage }}"
         state: present

     - name: To copy a file named "{{ myfile }}"
       copy:
         src: "/opt/{{ myfile }}"
         dest: /opt/{{ myfile }}
         mode: 0644
